baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"

relativeURLs=true
disableRSS=true
metaDataFormat = "toml"

[params]
    description = "La description"
    generator="Hugo 0.14"
    author = "Erik Aouizerate"
    subdomain = ""
    images=["img/home_1.jpg","img/home_2.jpg","img/home_3.jpg","img/home_4.jpg"]
    image="img/home_profil.jpg"

[[menu.main]]
    name = "PRESTATIONS"
    url = "/prestations/"
    identifier = "prestations"
    weight = 10
[[menu.main]]
    name = "PHOTOS"
    url = "/photos/"
    identifier = "photos"
    weight = 20
[[menu.main]]
    name = "AGENDA"
    url = "/agenda/"
    identifier = "agenda"
    weight = 30
[[menu.main]]
    name = "RÉFÉRENCES"
    url = "/references/"
    identifier = "references"
    weight = 40
[[menu.main]]
    name = "CONTACT"
    url = "/contact/"
    identifier = "contact"
    weight = 50