baseurl = "http://manoel-artiste.fr/"
languageCode = "en-us"
title = "Jongleur, Spectacle de feu et Sculpteur de ballons à Paris"

relativeURLs=true
disableRSS=true
metaDataFormat = "toml"

[params]
    description = "Retrouvez des spectacles en jongleur, sculpteur de ballons et des spectacles de feu, à Paris et partout en France"
    generator="Hugo 0.14"
    author = "Manoel Mathis"
    subdomain = ""
    images=["img/home/home_1.jpg","img/home/home_2.jpg","img/home/home_3.jpg","img/home/home_4.jpg","img/home/home_5.jpg","img/home/home_6.jpg","img/home/home_7.jpg","img/home/home_8.jpg"]
    image="img/home/BQ_anniere_jongle_feu_ballons.jpg"
    local = "fr"

[[menu.main]]
    name = "PRESTATIONS"
    url = "/prestations/"
    identifier = "prestations"
    weight = 10
[[menu.main]]
    name = "PHOTOS"
    url = "/photos/all"
    identifier = "photos"
    weight = 20
[[menu.main]]
    name = "AGENDA"
    url = "/agenda/"
    identifier = "agenda"
    titlePage = "YYEEESSS"
    weight = 30
[[menu.main]]
    name = "RÉFÉRENCES"
    url = "/references/"
    identifier = "references"
    weight = 40
[[menu.main]]
    name = "CONTACT"
    url = "/contact/"
    identifier = "contact"
    weight = 50